<footer role="contentinfo">
  <ul>
    <li><a href="/symbol/index.html" target="_blank">NTT西日本グループ　シンボルチーム</a></li>
    <li> <small>&copy; 2017　西日本電信電話株式会社</small></li>
  </ul>
</footer>
<!--<a href="/symbol/hp/baseball/games/2016/city/hero.html" id="hero"><img src="/symbol/hp/baseball/games/2016/city/img/common/hero.png" width="160" height="160" alt="ヒーローインタビュー"></a>-->
<p id="pagetop"><a href="#top">▲</a></p>