<header role="banner" id="top">
	<h1><a href="/" target="_blank"><img src="/symbol/hp/baseball/games/2013/city/img/common/ci.gif" width="148" height="46" alt="NTT西日本"></a></h1>
	<ul id="topnavi">
		<li><a href="/" target="_blank">NTT西日本公式トップ</a></li>
		<li><a href="/share/aboutsite.html" target="_blank">このサイトについて</a></li>
		<li><a href="/share/privacy.html" target="_blank">プライバシーポリシー</a></li>
	</ul>
</header>
<nav id="global" role="navigation">
	<h2><a href="/symbol/hp/baseball/games/2017/city/index.html"><img src="img/common/logo.png" alt="第43回 社会人野球日本選手権大会"></a></h2>
	<dl>
		<dt class="menu-trigger">
			<span></span>
			<span></span>
			<span></span>
			<i>menu</i>
		</dt>
		<dd>
			<dl>
				<dt>メインメニュー<i>Main menu</i></dt>
				<dd class="index"><a href="/symbol/hp/baseball/games/2017/city/index.html"><span class="fa fa-home"></span>トップページ<i>Top Page</i></a></dd>
				<dd class="tournament"><a href="/symbol/hp/baseball/games/2017/city/tournament.html"><span class="fa fa-sitemap"></span>トーナメント表<i>Tournament Bracket</i></a></dd>
				<dd class="results"><a href="/symbol/hp/baseball/games/2017/city/results.html"><span class="fa fa-list-ol"></span>試合結果<i>Results</i></a></dd>
				<dd class="gallery"><a href="/symbol/hp/baseball/games/2017/city/gallery.html"><span class="fa fa-camera"></span>ギャラリー<i>Photo gallery</i></a></dd>
				<dd class="aid"><a href="/symbol/hp/baseball/games/2017/city/aid.html"><span class="fa fa-volume-up"></span>応援ガイド<i>Guidance of aid</i></a></dd>
				<dd class="access"><a href="/symbol/hp/baseball/games/2017/city/access.html"><span class="fa fa-map-marker"></span>アクセスガイド<i>Guidance to a stadium</i> </a></dd>
			</dl>
		</dd>
		<dd>
			<dl>
				<dt>トピックス <i>Topics</i></dt>
				<!--<dd class="hero"><a href="/symbol/hp/baseball/games/2017/city/hero.html"><span class="fa fa-microphone"></span>ヒーローインタビュー<i>Hero Interview</i></a></dd>-->
				<dd class="mascot"><a href="/symbol/hp/baseball/games/2017/city/mascot.html"><span class="fa fa-pencil-square-o"></span>マスコットの会場リポート<i>The mascot's game report</i></a></dd>
				<dd class="history"><a href="/symbol/hp/baseball/games/2017/city/history.html"><span class="fa fa-trophy"></span>都市対抗野球とNTTグループの歴史<i>History</i></a></dd>
				<dd class="past"><a href="/symbol/hp/baseball/games/2017/city/past.html"><span class="fa fa-book"></span>NTT西日本 過去の戦績<i>The past results</i></a></dd>
			</dl>
		</dd>
		<dd>
			<dl>
				<dt>関連ページ <i>External link</i></dt>
				<dd><a href="http://symbol.ntt-west.co.jp/nw/baseball/pitcher.php" target="_blank"><span class="fa fa-users"></span>NTT西日本硬式野球部 選手紹介</a></dd>
				<dd><a href="https://symbol.ntt-west.co.jp/nw/sendmessage.php?tid=baseball" target="_blank"><span class="fa fa-comments"></span>応援メッセージを送る</a></dd>
				<dd><a href="http://www.ntt-west.co.jp/symbol/mobile_mail/index.html" target="_blank" class="banner"><span class="fa fa-envelope-o"></span>速報メールマガジン ご登録</a></dd>
				<dd><a href="http://www.ntt-west.co.jp/symbol/fan/index.html" target="_blank" class="banner"><span class="fa fa-user-plus"></span>ファンクラブ ご登録</a></dd></dd>
			</dl>
		</dd>
	</dl>
	<img src="img/common/live.png" id="live">
</nav>